version: '3'

services:

  registry:
    container_name: registry-server
    image: registry:latest
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./registry-data:/var/lib/registry
    networks:
      - registry

  registry-ui:
    container_name: registry-web
    image: hyper/docker-registry-web:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - REGISTRY_NAME=localhost:5000
      - REGISTRY_URL=http://registry:5000/v2
    networks:
      - registry

networks:
  registry: