- name: Configurate the Debian 11
  hosts: all
  become: true
  tasks:
    - name: Add the user 'debian' with a bash shell, appending the group 'sudo'
      ansible.builtin.user:
        name: debian
        password: ""
        shell: /bin/bash
        groups: sudo
        append: true
        create_home: true
        home: /opt/debian

- name: Update and install applications  
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: "Update cache & Full system update"
      apt:
        update_cache: true
        upgrade: dist
        cache_valid_time: 3600
        force_apt_get: true
    - name: Update the repository cache and update package "nginx" to 
        latest version using default release squeeze-backport
      ansible.builtin.apt:
        name: nginx
        state: latest
        update_cache: true
    - name: Install latest version of "openjdk-11-jdk" ignoring "install-recommends"
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: latest
        install_recommends: no
    - name: Update apt cache and make sure maria-db, curl, htop, midnight commander, fail2ban, git, apt-transport-https, ca-certificates, lsb-release, gnupg are installed
      ansible.builtin.apt:
        name: "{{ item }}"
        update_cache: true
      loop:
        - mariadb-server
        - curl
        - htop
        - mc
        - fail2ban
        - git
        - apt-transport-https
        - ca-certificates
        - lsb-release
        - gnupg
    - name: Install apache httpd  (state=present is optional)
      ansible.builtin.apt:
        name: apache2
        state: present

- name: Docker installation
  hosts: all
  become: true
  tasks:
    - name: Add signing key
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present
    - name: Add repository into sources list
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker
    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: present
